baseURL = 'https://tmprk.github.io/psychopy-docs'
languageCode = 'en-us'
title = 'PsychoPy Log'
theme = 'hugo-book'

[params]
    BookTheme = 'auto'
    BookMenuBundle= '/menu'

[markup.goldmark.renderer]
    unsafe= true