baseURL = 'http://localhost:1313/psychopy-docs'
languageCode = 'en-us'
title = 'Psych 499 Log'
theme = 'hugo-book'

[params]
    BookTheme = 'auto'
    BookMenuBundle = '/menu'

[markup.goldmark.renderer]
    unsafe = true